### ISSUE TITLE
Login : espaces !

### ISSUE THREAD

**Issue by Araneide** [guimier/zzchat#2]
Il est possible d'utiliser l'espace comme caractère de début ou de fin du login. On peut aussi mettre plusieurs espaces au milieu à la suite. Celà peut entrainer des problèmes : login similaires par exemple "Lucien" et "Lucien "...

**Comment by guimier** [comment]
Oui, il faut supprimer les espaces en fin / normaliser les suites d’espaces à un seul.

**Comment by guimier** [comment]
Corrigé par 8d1573ee8816ac67256022ec4737bf2aa35f0c4e.
